version: "3"
services:
  hubervice:
    image: selenium/hub:3.14
  chromeservice:
    image: selenium/node-chrome:3.14
    depends_on:
      - hubervice
    environment:
      - HUB_HOST=hubervice
  firefoxservice:
    image: selenium/node-firefox:3.14
    depends_on:
      - hubervice
    environment:
      - HUB_HOST=hubervice
  flightbookingservice:
    image: chittesh/ixigonew:latest
    depends_on:
      - chromeservice
      - firefoxservice
    environment:
      - HUB_HOST=hubervice
    volumes:
      - ./testoutput:/usr/share/chittesh/test-output

